[package]
name = "heuristics"
version = "0.1.0"
authors = ["Simon Strassl <stuff@sigmoid.at>"]
edition = "2018"

[dependencies]
ndarray = "0.13.0"
clap = "2.33.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
log = "0.4.8"
env_logger = "0.7.1"
itertools = "0.9.0"

[profile.dev]
debug = true